---
settings:
  name: Astra Automation
  internal:
    pdf_enabled: true
    api_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    api_enabled: true
  rss_page: rn/whats_new.html
  versions:
  - version-number: '23.10'
    url: "/astra-automation"
  - version-number: '23.07'
    url: https://docs.netapp.com/us-en/astra-automation-2307/
  - version-number: '23.04'
    url: https://docs.netapp.com/us-en/astra-automation-2304/
  - version-number: '22.11'
    url: https://docs.netapp.com/us-en/astra-automation-2211/
  - version-number: '22.08'
    url: https://docs.netapp.com/us-en/astra-automation-2208/
  - version-number: '22.04'
    url: https://docs.netapp.com/us-en/astra-automation-2204/
  - version-number: '21.12'
    url: https://docs.netapp.com/us-en/astra-automation-2112/
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documentazione di Astra Control Automation
    url: "/index.html"
  - section: rn
  - section: intro
  - section: get-started
  - title: Implementazione REST di Astra
    entries:
    - section: rest-core
    - section: endpoints
    - section: additional
  - section: workflows_infra
  - section: workflows
  - section: python
  - section: reference
  - section: information
  - title: Note legali
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Inizia subito
    links:
    - title: Panoramica
      url: "/intro/overview.html"
    - title: Prima di iniziare
      url: "/get-started/before_get_started.html"
    - title: Ottieni un token API
      url: "/get-started/get_api_token.html"
    - title: Prima chiamata API
      url: "/get-started/first_call.html"
  - title: Design del SUPPORTO centrale
    links:
    - title: Servizi web REST
      url: "/rest-core/rest_web_services.html"
    - title: Dettagli HTTP
      url: "/rest-core/http_details.html"
    - title: Formato URL
      url: "/rest-core/url_format.html"
  - title: Considerazioni aggiuntive
    links:
    - title: Sicurezza RBAC
      url: "/additional/rbac.html"
    - title: Lavorare con le raccolte
      url: "/additional/work_with_collections.html"
    - title: Diagnostica e supporto
      url: "/additional/diagnostics_support.html"
    - title: Revocare un token API
      url: "/additional/revoke_token.html"
  - title: Risorse
    links:
    - title: Risorse E raccolte REST
      url: "/rest-core/resources_collections.html"
    - title: Riepilogo delle risorse API di Astra
      url: "/endpoints/resources.html"
  - title: Flussi di lavoro
    links:
    - title: Preparazione
      url: "/get-started/prepare_to_use_workflows.html"
    - title: Flussi di lavoro dell'infrastruttura
      url: "/workflows_infra/workflows_infra_before.html"
    - title: Workflow di gestione
      url: "/workflows/workflows_before.html"
  - title: Python
    links:
    - title: SDK NetApp Astra Control Python
      url: "/python/astra_toolkits.html"
    - title: Utilizzare Python in modo nativo
      url: "/python/python_before.html"
product-family:
  name: Astra
  repo: astra-family
