---
sidebar: sidebar 
permalink: rn/about.html 
keywords: about, about this release, current release 
summary: 'La documentazione di questo sito descrive l"API DI Astra Control REST e le relative tecnologie di automazione disponibili con Astra Control.' 
---
= A proposito di questa release
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La documentazione di questo sito descrive l'API DI Astra Control REST e le relative tecnologie di automazione incluse nelle release più recenti dei due modelli di implementazione di Astra Control.


NOTE: Ad ogni release di Astra Control viene assegnato un numero di versione del modulo *YY.MM*. Questo valore indica la versione in base all'anno (_YY_) e al mese (_MM_) in cui è diventata disponibile. Ad esempio, Astra Control Center 23.04 è stato rilasciato nell'aprile 2023.

.Cadenza di rilascio
In generale, gli aggiornamenti di Astra Control Service e Astra Control Center avvengono contemporaneamente. Tuttavia, Astra Control Service ha una cadenza di rilascio accelerata che può portare a uno o più aggiornamenti incrementali oltre la versione più recente di Astra Control Center.

Poiché questo sito documenta l'API REST per entrambi i modelli di implementazione, alcune funzionalità potrebbero essere disponibili solo con la versione più recente di Astra Control Service. Le eventuali differenze tra i due modelli di implementazione vengono notate in base alle necessità.

.Implementazioni di Astra Control
La documentazione di questo sito si applica alle seguenti release di Astra Control:

* Servizio di controllo Astra 23.06
* Centro di controllo Astra 23.04


.Ulteriori informazioni
Per ulteriori informazioni sulle versioni attuali e precedenti di Astra Control, consultare le pagine e i siti seguenti.

* link:../rn/whats_new.html["Novità dell'API REST di Astra Control"]
* link:../endpoints/resources.html["Risorse REST ed endpoint"]
* https://docs.netapp.com/us-en/astra-control-center/["Documentazione di Astra Control Center 23.04"^]
* https://docs.netapp.com/us-en/astra-control-service/["Documentazione di Astra Control Service 23.06"^]
* link:../aa-earlier-versions.html["Versioni precedenti della documentazione di Astra Automation"]


.Aiutaci a migliorare la documentazione
Seguici su Twitter *@NetAppDoc* per ricevere notifiche sulla documentazione NetApp. Puoi anche fornire un feedback diventando un link:https://docs.netapp.com/us-en/contribute/["Collaboratore di GitHub"^] oppure inviare un'e-mail all'indirizzo _doccomments@netapp.com_.
