---
sidebar: sidebar 
permalink: workflows_infra/wf_man_cluster.html 
keywords:  
summary: È possibile gestire un cluster Kubernetes in modo da eseguire le operazioni di protezione dei dati. 
---
= Gestire un cluster
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile gestire un cluster Kubernetes in modo da poter eseguire la protezione dei dati.



=== 1. Selezionare il cluster da gestire

Eseguire il flusso di lavoro link:../workflows_infra/wf_list_clusters.html["Elencare i cluster"] e selezionare il cluster desiderato. La proprietà `managedState` del cluster deve essere `unmanaged`.



=== 2. Se si desidera, selezionare la classe di storage

Eseguire il flusso di lavoro come opzione link:../workflows_infra/wf_list_storage_classes.html["Elencare le classi di storage"] e selezionare la classe di storage desiderata.


NOTE: Se non si fornisce una classe di storage durante la chiamata per gestire il cluster, viene utilizzata la classe di storage predefinita.



=== 3. Gestire il cluster

Eseguire la seguente chiamata API REST per gestire il cluster.

[cols="1,6"]
|===
| Metodo HTTP | Percorso 


| POST | /Accounts/{account_id}/topology/v1/managedClusters 
|===


===== Esempio di input JSON

[source, json]
----
{
  "type": "application/astra-managedCluster",
  "version": "1.0",
  "id": "d0fdf455-4330-476d-bb5d-4d109714e07d"
}
----


===== Esempio di arricciamento

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/topology/v1/managedClusters' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --data @JSONinput
----