---
sidebar: sidebar 
permalink: workflows/wf_create_snapshot.html 
keywords:  
summary: 'È possibile creare uno snapshot per un"applicazione specifica.' 
---
= Creare un'istantanea per un'applicazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile creare uno snapshot per un'applicazione specifica.



=== Prima di iniziare

È necessario disporre dell'ID dell'applicazione per la quale si desidera creare uno snapshot. Se necessario, è possibile utilizzare il flusso di lavoro link:wf_list_man_apps.html["Elencare le applicazioni"] per individuare l'applicazione.



=== 1. Creare un'istantanea

Eseguire la seguente chiamata API REST.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| POST | /Accounts/{account_id}/k8s/v1/apps/{app_id}/appSnap 
|===


===== Parametri di input aggiuntivi

Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| id app | Percorso | Sì | Identifica l'applicazione gestita in cui verrà creata l'istantanea. 


| JSON | Corpo | Sì | Fornisce i parametri per lo snapshot. Vedere l'esempio riportato di seguito. 
|===


===== Esempio di input JSON

[source, json]
----
{
  "type": "application/astra-appSnap",
  "version": "1.1",
  "name": "snapshot-david-1"
}
----


===== Esempio di curl: Creare un'istantanea per l'applicazione

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appSnaps' --header 'Content-Type: application/astra-appSnap+json' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --data @JSONinput
----