---
sidebar: sidebar 
permalink: workflows/wf_clone_app_backup.html 
keywords:  
summary: È possibile creare una nuova applicazione clonandola da un backup. 
---
= Clonare un'applicazione da un backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile creare una nuova applicazione clonandola da un backup.



=== Prima di iniziare

Tenere presente quanto segue a proposito di questo flusso di lavoro:

* Viene utilizzato un backup dell'applicazione
* L'operazione di cloni viene eseguita all'interno dello stesso cluster



NOTE: Per clonare un'applicazione in un cluster diverso, è necessario aggiornare `clusterId` Nell'input JSON appropriato per il proprio ambiente.



=== 1. Selezionare l'applicazione da clonare

Eseguire il flusso di lavoro link:wf_list_man_apps.html["Elencare le applicazioni"] e selezionare l'applicazione che si desidera clonare. Per la chiamata DI PAUSA utilizzata per clonare l'applicazione sono necessari diversi valori delle risorse.



=== 2. Selezionare il backup da utilizzare

Eseguire il flusso di lavoro link:wf_list_backups.html["Elencare i backup"] e selezionare il backup che si desidera utilizzare.



=== 3. Clonare l'applicazione

Eseguire la seguente chiamata API REST.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| POST | /accounts/{account_id}/k8s/v2/qpps 
|===


===== Parametri di input aggiuntivi

Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| JSON | Corpo | Sì | Fornisce i parametri per l'applicazione clonata. Vedere l'esempio riportato di seguito. 
|===


===== Esempio di input JSON

[source, json]
----
{
  "type": "application/astra-app",
  "version": "2.0",
  "name": "mysql-clone3",
  "clusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "sourceClusterID": "30880586-d579-4d27-930f-a9633e59173b",
  "namespace": "mysql",
  "backupID": "e24515bd-a28e-4b28-b832-f3c74dbf32fb"
}
----


===== Esempio di curl: Clonare un'applicazione da un backup

[source, curl]
----
curl --location -i --request POST 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v2/apps' --header 'Content-Type: application/astra-app+json' --header '*/*' --header 'Authorization: Bearer <API_TOKEN>' --data @JSONinput
----