---
sidebar: sidebar 
permalink: workflows/wf_delete_backup.html 
keywords:  
summary: 'È possibile eliminare un backup associato a un"applicazione.' 
---
= Eliminare un backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile eliminare un backup associato a un'applicazione.



=== Prima di iniziare

È necessario disporre di quanto segue:

* ID dell'applicazione proprietaria del backup. Se necessario, è possibile utilizzare il flusso di lavoro link:wf_list_man_apps.html["Elencare le applicazioni"] per individuare l'applicazione.
* ID del backup che si desidera eliminare. Se necessario, è possibile utilizzare il flusso di lavoro link:wf_list_backups.html["Elencare i backup"] per individuare lo snapshot.




=== 1. Eliminare il backup

Eseguire la seguente chiamata API REST.


NOTE: È possibile forzare l'eliminazione di un backup non riuscito utilizzando l'intestazione della richiesta opzionale come descritto di seguito.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| ELIMINARE | /Accounts/{account_id}/k8s/v1/apps/{app_id}/appBackups/{appBackup_id} 
|===


===== Parametri di input aggiuntivi

Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| id app | Percorso | Sì | Identifica l'applicazione gestita proprietaria del backup. 


| id backup | Percorso | Sì | Identifica il backup da eliminare. 


| forza eliminazione | Intestazione | No | Utilizzato per forzare l'eliminazione di un backup non riuscito. 
|===


===== Esempio di curl: Eliminare un singolo backup per l'applicazione

[source, curl]
----
curl --location -i --request DELETE 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appBackups/<BACKUP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Esempio di curl: Eliminare un singolo backup per l'applicazione con l'opzione force

[source, curl]
----
curl --location -i --request DELETE 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appBackups/<BACKUP_ID>' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>' --header 'Force-Delete: true'
----