---
sidebar: sidebar 
permalink: workflows/wf_list_backups.html 
keywords:  
summary: 'È possibile elencare i backup creati per un"applicazione specifica.' 
---
= Elencare i backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile elencare i backup creati per un'applicazione specifica.



=== Prima di iniziare

È necessario disporre dell'ID dell'applicazione per cui si desidera elencare i backup. Se necessario, è possibile utilizzare il flusso di lavoro link:wf_list_man_apps.html["Elencare le applicazioni"] per individuare l'applicazione.



=== 1. Elencare i backup

Eseguire la seguente chiamata API REST.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| OTTIENI | /Accounts/{account_id}/k8s/v1/apps/{app_id}/appBackups 
|===


===== Parametri di input aggiuntivi

Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| id app | Percorso | Sì | Identifica l'applicazione gestita proprietaria dei backup elencati. 
|===


===== Esempio di curl: Restituire tutti i backup per l'applicazione

[source, curl]
----
curl --location -i --request GET 'https://astra.netapp.io/accounts/<ACCOUNT_ID>/k8s/v1/apps/<APP_ID>/appBackups' --header 'Accept: */*' --header 'Authorization: Bearer <API_TOKEN>'
----


===== Esempio di output JSON

[source, json]
----
{
    "items": [
        {
            "type": "application/astra-appBackup",
            "version": "1.1",
            "id": "8edeb4a4-fd8b-4222-a559-1013145b28fc",
            "name": "backup-david-oct28-1",
            "bucketID": "a443e58f-59bd-4d45-835a-1bc7813f659a",
            "snapshotID": "dfe237cb-57b7-4576-af4d-00ba3a8f2828",
            "state": "completed",
            "stateUnready": [],
            "hookState": "success",
            "totalBytes": 205219132,
            "bytesDone": 205219132,
            "percentDone": 100,
            "metadata": {
                "labels": [
                    {
                        "name": "astra.netapp.io/labels/read-only/triggerType",
                        "value": "backup"
                    }
                ],
                "creationTimestamp": "2022-10-28T21:58:37Z",
                "modificationTimestamp": "2022-10-28T21:58:55Z",
                "createdBy": "a530e865-23e8-4e2e-8020-e92c419a3867"
            }
        }
    ],
    "metadata": {}
}
----