---
sidebar: sidebar 
permalink: workflows/wf_manage_app.html 
keywords:  
summary: 'È possibile creare un"applicazione gestita in base a un"applicazione già nota ad Astra in uno spazio dei nomi specifico. Quando un"applicazione viene gestita o definita in Astra, è possibile proteggerla eseguendo backup e snapshot.' 
---
= Gestire un'applicazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile creare un'applicazione gestita in base a un'applicazione già nota ad Astra in uno spazio dei nomi specifico. Quando un'applicazione viene gestita o definita in Astra, è possibile proteggerla eseguendo backup e snapshot.



== Passaggio 1: Selezionare lo spazio dei nomi

Eseguire il flusso di lavoro link:../workflows/wf_list_namespaces.html["Elencare gli spazi dei nomi"] e selezionare lo spazio dei nomi.



== Passaggio 2: Selezionare il cluster

Eseguire il flusso di lavoro link:../workflows_infra/wf_list_clusters.html["Elencare i cluster"] e selezionare il cluster.



== Passaggio 3: Gestione dell'applicazione

Eseguire la seguente chiamata API REST per gestire l'applicazione.

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| POST | /accounts/{account_id}/k8s/v2/apps 
|===
.Parametri di input aggiuntivi
Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| JSON | Corpo | Sì | Fornisce i parametri necessari per identificare l'applicazione da gestire. Vedere l'esempio riportato di seguito. 
|===
.Esempio di curl: Gestire un'applicazione
[source, curl]
----
curl --request POST \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v2/apps" \
--include \
--header "Content-Type: application/astra-app+json" \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN" \
--data @JSONinput
----
.Esempio di input JSON
[source, json]
----
{
  "clusterID": "7ce83fba-6aa1-4e0c-a194-26e714f5eb46",
  "name": "subtext",
  "namespaceScopedResources": [{"namespace": "kube-matrix"}],
  "type": "application/astra-app",
  "version": "2.0"
}
----