---
sidebar: sidebar 
permalink: workflows/wf_unmanage_app.html 
keywords:  
summary: 'Puoi rimuovere un"applicazione gestita quando non è più necessaria. La rimozione di un"applicazione gestita elimina anche le pianificazioni associate.' 
---
= Annullare la gestione di un'applicazione
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Puoi rimuovere un'applicazione gestita quando non è più necessaria. La rimozione di un'applicazione gestita elimina anche le pianificazioni associate.



== Prima di iniziare

Devi disporre dell'ID dell'applicazione che desideri annullare la gestione. Se necessario, è possibile utilizzare il flusso di lavoro link:wf_list_man_apps.html["Elencare le applicazioni"] per individuare l'applicazione.

I backup e le snapshot dell'applicazione non vengono rimossi automaticamente quando vengono eliminati. Se non sono più necessari backup e snapshot, è necessario eliminarli prima di rimuovere l'applicazione.



== Annullare la gestione dell'app

Eseguire la seguente chiamata API REST per rimuovere l'applicazione.

.Metodo HTTP ed endpoint
Questa chiamata API REST utilizza il metodo e l'endpoint seguenti.

[cols="25,75"]
|===
| Metodo HTTP | Percorso 


| ELIMINARE | /accounts/{account_id}/k8s/v2/apps/{app_id} 
|===
.Parametri di input aggiuntivi
Oltre ai parametri comuni a tutte le chiamate API REST, negli esempi di curl vengono utilizzati anche i seguenti parametri.

[cols="25,10,10,55"]
|===
| Parametro | Tipo | Obbligatorio | Descrizione 


| id app | Percorso | Sì | Identifica l'applicazione da rimuovere. 
|===
.Esempio di curl: Rimuovere un'applicazione gestita
[source, curl]
----
curl --request DELETE \
--location "https://astra.netapp.io/accounts/$ACCOUNT_ID/k8s/v2/apps/$APP_ID" \
--include \
--header "Accept: */*" \
--header "Authorization: Bearer $API_TOKEN"
----